#SPDX-License-Identifier: MIT-0
---
# tasks file for ./test/roles/myrole

- name: "Install nginx via apt"
  ansible.builtin.apt:
    name:
      - nginx
      - curl
    state: "latest"
    update_cache: true

- name: Create index.html using Jinja2
  ansible.builtin.template:
    src: templates/index.j2
    dest: /var/www/html/index.html